# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f829f4623d1ffd8ad2345f5822e91843ed76d5fe6efa19f2a0ecff8355222b22bf445e93b7f51c5422a76b673f9220cdae01b3bcf4a85762d8090137c7b4954

test:
  secret_key_base: 5cea2bd3036f5d69485907e535ca1ab42e79fb24e8fb2902d7f1a83016ccaa4f8099b3c068ee401d2bef70b0a32fe6dcacca36035cc4a447cdd7c2aa5f44b71f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
